Resources:
  checkStoreHoursHandlerServiceRole828F3182:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/checkStoreHoursHandler/ServiceRole/Resource
  checkStoreHoursHandler2C82889A:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3Bucket842AB57C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3VersionKey7440F4A6
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3VersionKey7440F4A6
      Role:
        Fn::GetAtt:
          - checkStoreHoursHandlerServiceRole828F3182
          - Arn
      Handler: orderPizza.handler
      Runtime: nodejs12.x
    DependsOn:
      - checkStoreHoursHandlerServiceRole828F3182
    Metadata:
      aws:cdk:path: TheStateMachineStack/checkStoreHoursHandler/Resource
      aws:asset:path: asset.3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2
      aws:asset:property: Code
  checkDeliveryTypeHandlerServiceRole87A645B1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/checkDeliveryTypeHandler/ServiceRole/Resource
  checkDeliveryTypeHandler71905A16:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3Bucket842AB57C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3VersionKey7440F4A6
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3VersionKey7440F4A6
      Role:
        Fn::GetAtt:
          - checkDeliveryTypeHandlerServiceRole87A645B1
          - Arn
      Handler: orderPizza.handler
      Runtime: nodejs12.x
    DependsOn:
      - checkDeliveryTypeHandlerServiceRole87A645B1
    Metadata:
      aws:cdk:path: TheStateMachineStack/checkDeliveryTypeHandler/Resource
      aws:asset:path: asset.3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2
      aws:asset:property: Code
  emailPizzaHandlerServiceRole9F9BBA4A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/emailPizzaHandler/ServiceRole/Resource
  emailPizzaHandlerDC7C690A:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3Bucket37CB776A
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3VersionKeyB761AB89
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3VersionKeyB761AB89
      Role:
        Fn::GetAtt:
          - emailPizzaHandlerServiceRole9F9BBA4A
          - Arn
      Handler: emailPizza.handler
      Runtime: nodejs12.x
    DependsOn:
      - emailPizzaHandlerServiceRole9F9BBA4A
    Metadata:
      aws:cdk:path: TheStateMachineStack/emailPizzaHandler/Resource
      aws:asset:path: asset.57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09
      aws:asset:property: Code
  webPostPizzaHandlerServiceRole36375B99:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/webPostPizzaHandler/ServiceRole/Resource
  webPostPizzaHandlerC2594DFC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3Bucket37CB776A
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3VersionKeyB761AB89
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3VersionKeyB761AB89
      Role:
        Fn::GetAtt:
          - webPostPizzaHandlerServiceRole36375B99
          - Arn
      Handler: webPostPizza.handler
      Runtime: nodejs12.x
    DependsOn:
      - webPostPizzaHandlerServiceRole36375B99
    Metadata:
      aws:cdk:path: TheStateMachineStack/webPostPizzaHandler/Resource
      aws:asset:path: asset.57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09
      aws:asset:property: Code
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/Resource
  StateMachineRoleDefaultPolicyDF1E6607:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - checkStoreHoursHandler2C82889A
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - checkDeliveryTypeHandler71905A16
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - emailPizzaHandlerDC7C690A
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - webPostPizzaHandlerC2594DFC
                - Arn
        Version: "2012-10-17"
      PolicyName: StateMachineRoleDefaultPolicyDF1E6607
      Roles:
        - Ref: StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Check Store Hours","States":{"Check Store Hours":{"Next":"Store is open?","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$","ResultPath":"$.storeIsOpen","Resource":"'
            - Fn::GetAtt:
                - checkStoreHoursHandler2C82889A
                - Arn
            - '"},"Store is open?":{"Type":"Choice","Choices":[{"Variable":"$.storeIsOpen","BooleanEquals":false,"Next":"Cloud pizzas can only be delivered on odd numbered epoch times, try again when the store is open."}],"Default":"Check Delivery Type"},"Check Delivery Type":{"Next":"Can deliver?","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$","ResultPath":"$.deliveryType","Resource":"'
            - Fn::GetAtt:
                - checkDeliveryTypeHandler71905A16
                - Arn
            - '"},"Can deliver?":{"Type":"Choice","Choices":[{"Variable":"$.addressType","StringEquals":"email","Next":"Email Pizza Delivery"},{"Variable":"$.addressType","StringEquals":"endpoint","Next":"Web Post Pizza Delivery"}]},"Email Pizza Delivery":{"End":true,"Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$","ResultPath":"$.emailResult","Resource":"'
            - Fn::GetAtt:
                - emailPizzaHandlerDC7C690A
                - Arn
            - '"},"Web Post Pizza Delivery":{"End":true,"Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$","ResultPath":"$.webPostResult","Resource":"'
            - Fn::GetAtt:
                - webPostPizzaHandlerC2594DFC
                - Arn
            - '"},"Cloud pizzas can only be delivered on odd numbered epoch times, try again when the store is open.":{"Type":"Fail","Error":"Pizza order canceled: Store closed","Cause":"The store was closed"}},"TimeoutSeconds":300}'
      StateMachineType: EXPRESS
      TracingConfiguration:
        Enabled: true
    DependsOn:
      - StateMachineRoleDefaultPolicyDF1E6607
      - StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Resource
  HttpApiRole79B5C31A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: states:StartSyncExecution
                Effect: Allow
                Resource:
                  Ref: StateMachine2E01A3A5
            Version: "2012-10-17"
          PolicyName: AllowSFNExec
    Metadata:
      aws:cdk:path: TheStateMachineStack/HttpApiRole/Resource
  thestatemachineapi69C81CC4:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: the-state-machine-api
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/Resource
  thestatemachineapiDefaultStageE23A2C15:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/DefaultStage/Resource
  Integ:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      IntegrationType: AWS_PROXY
      ConnectionType: INTERNET
      CredentialsArn:
        Fn::GetAtt:
          - HttpApiRole79B5C31A
          - Arn
      IntegrationSubtype: StepFunctions-StartSyncExecution
      PayloadFormatVersion: "1.0"
      RequestParameters:
        Input: $request.body
        StateMachineArn:
          Ref: StateMachine2E01A3A5
      TimeoutInMillis: 10000
    Metadata:
      aws:cdk:path: TheStateMachineStack/Integ
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: Integ
    Metadata:
      aws:cdk:path: TheStateMachineStack/DefaultRoute
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAACl1Q0WrDMAz8lr477rKxwd7WBsYKGyvZF2iOmqpJ7GDJKSXk32e7K4w93Z04SSeVuiyf9d3qBc5cmKZbz8Z51POXgOnUhhkl0pZsqypnWXwwoqqD3YOHAQV9Ep9BxpDLNbIL3mDi0d+QkLOLSsPnHobvBvT8GqxJ5eS58UURDHquXZ9bM+5dT+aSl2W2KH4oICVinYNFrbfBdChbYFQsOB5+53EhwB3r97xzZyfX/TPEHEC9qo6OYtx4o+AHmCPZHOCvjvFHaqM+w2W61/ObyLgZKdkSJJledOu7kp0VbD3c7qxdEFyWRVnXoD7xeiqfdPmoy9WJiQofrNCAur7iD49nWtyVAQAA
    Metadata:
      aws:cdk:path: TheStateMachineStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3Bucket842AB57C:
    Type: String
    Description: S3 bucket for asset "3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2"
  AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2S3VersionKey7440F4A6:
    Type: String
    Description: S3 key for asset version "3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2"
  AssetParameters3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2ArtifactHashC439547F:
    Type: String
    Description: Artifact hash for asset "3aa19ed72e8ea76c34c614248d6c29318de75b3305cad99074ec671d6e8ff2c2"
  AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3Bucket37CB776A:
    Type: String
    Description: S3 bucket for asset "57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09"
  AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09S3VersionKeyB761AB89:
    Type: String
    Description: S3 key for asset version "57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09"
  AssetParameters57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09ArtifactHash9C14D186:
    Type: String
    Description: Artifact hash for asset "57c0458c31e08a91a49324bae7ec70efda75c2d6846adfba6535e5632e1d7a09"
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: thestatemachineapi69C81CC4
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

